apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: book-manager
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: http
